# Generated by Django 5.0.7 on 2024-08-08 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empresarios', '0003_metricas'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Metricas',
        ),
    ]
